<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="A2ML30049" name="io.mosip.authentication.tests.DemographicAuthentication" tests="37" failures="0" timestamp="12 Jul 2019 07:44:48 GMT" time="38.022" errors="37">
  <testcase name="Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For IntegrationTest_UIN_Pos_01" time="0.742" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For IntegrationTest_UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_Address_With_primary and secondary lang_smoke_pos_01" time="0.949" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_primary and secondary lang_smoke_pos_01 -->
  <testcase name="Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For VID_Pos_04" time="0.744" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For VID_Pos_04 -->
  <testcase name="Authentication_Demographic_DateOfBirth_smoke_For IntegrationTest_UIN_Pos_01" time="7.477" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_DateOfBirth_smoke_For IntegrationTest_UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_Address_With_primary and secondary lang_for VID_smoke_pos_38" time="1.131" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_primary and secondary lang_for VID_smoke_pos_38 -->
  <testcase name="Authentication_Demographic_fullAddress_With_primary and secondary lang_smoke_pos" time="0.932" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_primary and secondary lang_smoke_pos -->
  <testcase name="Authentication_Demographic_Name_UnMarried Female_Tittle_Normalisation_Smoke_For VID_Pos_06" time="0.941" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_UnMarried Female_Tittle_Normalisation_Smoke_For VID_Pos_06 -->
  <testcase name="Authentication_Demographic_Gender_With french language_smoke_For VID_Pos_28" time="0.730" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With french language_smoke_For VID_Pos_28 -->
  <testcase name="Authentication_Demographic_Gender_With french language_smoke_For UIN_Pos_03" time="0.881" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With french language_smoke_For UIN_Pos_03 -->
  <testcase name="Authentication_Demographic_Name_WithSecLang_Smoke_For UIN_Pos" time="0.846" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_WithSecLang_Smoke_For UIN_Pos -->
  <testcase name="Autheticate_Authentication_Demographic_Name_smoke_For VID_Pos_19" time="0.710" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Autheticate_Authentication_Demographic_Name_smoke_For VID_Pos_19 -->
  <testcase name="Authentication_Demographic_fullAddress_With_primary lang_smoke_for_VID_pos" time="0.733" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_primary lang_smoke_for_VID_pos -->
  <testcase name="Authentication_Demographic_Address_With_primary lang_smoke_pos_02" time="0.846" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_primary lang_smoke_pos_02 -->
  <testcase name="Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For VID_Pos_01" time="0.944" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For VID_Pos_01 -->
  <testcase name="Authentication_Demographic_fullAddress_With_primary and secondary lang_smoke_for_VID_pos" time="0.915" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_primary and secondary lang_smoke_for_VID_pos -->
  <testcase name="Authentication_Demographic_Gender_With both language_smoke_For UIN_Pos_01" time="0.836" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With both language_smoke_For UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_EmailId_smoke_For IntegrationTest_UIN_Pos_01" time="0.825" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_EmailId_smoke_For IntegrationTest_UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_Age_smoke_For IntegrationTest_UIN_Pos" time="1.095" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Age_smoke_For IntegrationTest_UIN_Pos -->
  <testcase name="Authentication_Demographic_Name_UnMarried Female_Tittle_Normalisation_Smoke_For UIN_Pos_06" time="1.464" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_UnMarried Female_Tittle_Normalisation_Smoke_For UIN_Pos_06 -->
  <testcase name="Authentication_Demographic_fullAddress_With_secondary lang_smoke_for_VID_pos" time="0.802" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_secondary lang_smoke_for_VID_pos -->
  <testcase name="Authentication_Demographic_EmailId_smoke_For VID_Pos_21" time="0.921" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_EmailId_smoke_For VID_Pos_21 -->
  <testcase name="Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For IntegrationTest_UIN_Pos_04" time="0.828" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_Male_Tittle_Normalisation_Smoke_For IntegrationTest_UIN_Pos_04 -->
  <testcase name="Authentication_Demographic_Name_Female_Tittle_Normalisation_Smoke_For UIN_Pos_05" time="0.818" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_Female_Tittle_Normalisation_Smoke_For UIN_Pos_05 -->
  <testcase name="Authentication_Demographic_Name_smoke_For UIN_Pos_01" time="0.810" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_smoke_For UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_Address_With_primary lang_For VID_smoke_pos_39" time="0.818" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_primary lang_For VID_smoke_pos_39 -->
  <testcase name="Authentication_Demographic_PhoneNumber_smoke_For VID_Pos_21" time="0.831" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_PhoneNumber_smoke_For VID_Pos_21 -->
  <testcase name="Authentication_Demographic_Address_With_secondary lang_smoke_pos_40" time="0.689" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_secondary lang_smoke_pos_40 -->
  <testcase name="Authentication_Demographic_Gender_With both language_smoke_For VID_Pos_26" time="0.674" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With both language_smoke_For VID_Pos_26 -->
  <testcase name="Authentication_Demographic_Name_Female_Tittle_Normalisation_Smoke_For VID_Pos_05" time="0.711" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Name_Female_Tittle_Normalisation_Smoke_For VID_Pos_05 -->
  <testcase name="Authentication_Demographic_PhoneNumber_smoke_For IntegrationTest_UIN_Pos_01" time="0.975" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_PhoneNumber_smoke_For IntegrationTest_UIN_Pos_01 -->
  <testcase name="Authentication_Demographic_fullAddress_With_secondary lang_smoke_pos" time="0.720" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_secondary lang_smoke_pos -->
  <testcase name="Authentication_Demographic_Address_With_secondary lang_smoke_pos_03" time="0.789" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Address_With_secondary lang_smoke_pos_03 -->
  <testcase name="Authentication_Demographic_Gender_With arabic language_smoke_For UIN_Pos_02" time="0.689" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With arabic language_smoke_For UIN_Pos_02 -->
  <testcase name="Authentication_Demographic_fullAddress_With_primary lang_smoke_pos" time="0.835" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_fullAddress_With_primary lang_smoke_pos -->
  <testcase name="Authentication_Demographic_Gender_With arabic language_smoke_For VID_Pos_27" time="0.825" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Gender_With arabic language_smoke_For VID_Pos_27 -->
  <testcase name="Authentication_Demographic_DateOfBirth_smoke_For VID_Pos_21" time="0.726" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_DateOfBirth_smoke_For VID_Pos_21 -->
  <testcase name="Authentication_Demographic_Age_smoke_For VID_Pos" time="0.820" classname="io.mosip.authentication.tests.DemographicAuthentication">
    <error type="io.mosip.authentication.fw.util.AuthenticationTestException" message="Failed at response output validation">
      <![CDATA[io.mosip.authentication.fw.util.AuthenticationTestException: Failed at response output validation
	at io.mosip.authentication.tests.DemographicAuthentication.demographicAuthenticationTest(DemographicAuthentication.java:185)
	at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:53)
	at io.mosip.authentication.e2e.AuthenticationE2E.performAuthE2E(AuthenticationE2E.java:10)
	at io.mosip.authentication.e2e.AuthenticationE2E.main(AuthenticationE2E.java:15)
]]>
    </error>
  </testcase> <!-- Authentication_Demographic_Age_smoke_For VID_Pos -->
</testsuite> <!-- io.mosip.authentication.tests.DemographicAuthentication -->
